[package]
name = "folding-core"
version = "0.1.0"
edition = "2024"

[features]
default = []
openmm = []

[dependencies]
folding-time = { path = "../time" }
folding-molecule = { path = "../molecule" }
