[package]
name = "folding-app"
version = "0.1.0"
edition = "2024"

[dependencies]
folding-core = { path = "../core" }
folding-time = { path = "../time" }
folding-molecule = { path = "../molecule" }
folding-interface = { path = "../interface" }
folding-sim = { path = "../sim" }
